### PR TITLE
Feature/cipheriv

### LINKED ISSUE #17: Use `cipheriv` instead of plain `cipher`
https://medium.com/@fhbro/crib-dragging-plain-text-attack-5a61a0bcd80d

https://stackoverflow.com/questions/25427935/node-js-create-initialization-vector-iv-from-random-source#29777716

Note that this will be a major change, as this changes the way the encrypted fields are stored. Also don't break backwards compatibility, i.e. use the regular cipher when no iv available...

### PR DESCRIPTION
**Pull request by vinczedani**
Closes #17 

This version is a proposal for an update in the next major version.

Interface change:
The secret needs to be fixed length, not like before. (maybe we can build in some method based on scrypt to keep the current interface)

The test might needs to be rewritten with a fixed iv, so we can use test like you did before (to expect exact outputs) now it is dynamic, it might not be the best solution, but it was the fastest I could do.

### CODE REVIEW

**Comment by vinczedani** [comment]
This PR contains my previous one. But after that one is merged, it will only contain the new changes only I think.

**Comment by vinczedani** [comment]
Damn, crypto.scrypt is introduced in node 10 only :/
I can fix it next week

**Comment by wheresvic** [comment]
Hi @vinczedani 

Thanks again for the second PR :)

I think that requiring a fixed length for the secret is a really big change as it breaks all backwards compatibility (I know you suggested a major version change but still people usually expect libraries to not significantly break under them). Moreover, from my limited research, it should be possible to use an algo that doesn't require a fixed length secret - could you look into this a bit more?

**Comment by wheresvic** [comment]
A second point regarding testing - rather than checking that the value is not the original string, we can also just run the decryption algorithm manually (we have the secret) and then assert that the result is the original string. It would lead to more robust tests.

**Comment by vinczedani** [comment]
Hi @wheresvic 
I created a solution to keep the current, "one string secret" input interface the package currently have. Also extended the test with your suggestion.
What do you think of this version?

**Comment by wheresvic** [comment]
@vinczedani Looks good, thanks again for contributing!

**Pull request merged**
