### PR TITLE
Added options for extra flexibility in mongoose-field-encryption behavior

### PR DESCRIPTION
**Pull request by adidaslevy**

### CODE REVIEW

**Comment by wheresvic** [comment]
@adidaslevy thanks for the PR - there are quite a few changes here so it might take me some time to go through all of them to make sure that we maintain backwards compatibility :)

Please bear with me!

**Comment by wheresvic** [comment]
@adidaslevy I do not see how the decryption for `encryptEachArrayItem` is being done. Could you add a test for this?

There are actually quite a few changes here. Ideally I would like to have a separate PR for each option so that we have a clean history and if there are problems we could quickly roll-back feature by feature. If you'd like to do this great otherwise I can also do it.

Thanks!

**Comment by adidaslevy** [comment]
> @adidaslevy I do not see how the decryption for `encryptEachArrayItem` is being done. Could you add a test for this?
> 
> There are actually quite a few changes here. Ideally I would like to have a separate PR for each option so that we have a clean history and if there are problems we could quickly roll-back feature by feature. If you'd like to do this great otherwise I can also do it.
> 
> Thanks!

Sure, NP. I'll submit the PRs for each option. 
Anyway, the priority issue here is the exception that is thrown, and needs to be taken care of. 

The rest will come later. I'll do it by next week (Got some pressure from peers - for other tasks)

**Comment by adidaslevy** [comment]
Closing the PR, 

I'm going to split it:
First - the null option and exception option (to my mind they should be bundled) will be reviewed, then the other stuff.

**Pull request closed without merging**
